spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

